[package]
name = "cli_org"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
env_logger = "0.11.5"
log = "0.4.22"
syntect = "5.2.0"
urlencoding = "2.1.3"
webbrowser = "1.0.2"
